services:
  - type: web
    name: lionstock-frontend
    region: ohio
    rootDir: .
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://lionstock-backend.onrender.com
